name: CI/CD Pipeline

on:
  push:
    branches: [ master ]


jobs:

  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python all python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64

      - name: Install Python Virtual ENV
        run: pip3 install virtualenv

      - name:  Setup Virtual env
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Activate and Install Depencies into Virtual env
        run: python -m venv venv && source venv/bin/activate &&
          pip3 install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

#       Install all the app dependencies
      - name: Install dependencies
        run: pip3 install -r requirements.txt

#       Build the app and run tests
      - name: Build and Run Test
        run: . venv/bin/activate && pytest
#
#      - name: Create Zipfile archive of Dependencies
#        run: |
#          cd ./venv/lib/python3.8/site-packages
#          zip -r9 ../../../../app.zip .

      - name : pip install
        run: |
          pip3 install --target python -r requirements.txt
          cd ./python
          zip -r9 ../app.zip .

      - name: Add App to Zipfile
        run: zip -g app.zip -r ./app main.py

      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app.zip


  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    if: github.ref == 'refs/heads/master'
    steps:

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Download Lambda app.zip
        uses: actions/download-artifact@v2
        with:
          name: app

      - name: Upload to S3
        run: aws s3 cp app.zip s3://fastapi-people-skills/app.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy new Lambda
        run: aws lambda update-function-code --function-name fastapi-people-skills-lambda --s3-bucket fastapi-people-skills --s3-key app.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
